apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: archrepod
bases:
  - ../../base
resources:
  - namespace.k8s.yaml
images:
  - name: docker.seankhliao.com/archrepod
    newName: europe-north1-docker.pkg.dev/com-seankhliao/kluster/archrepod
